# Generated by Django 6.0 on 2026-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('floor', 'Floor'), ('wall', 'Wall'), ('ceiling', 'Ceiling')], max_length=20)),
                ('preview_image', models.ImageField(upload_to='materials/')),
                ('ai_prompt_hint', models.TextField()),
            ],
        ),
    ]
