# Generated by Django 6.0 on 2026-02-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colors', models.JSONField()),
                ('preview_image', models.ImageField(blank=True, upload_to='color_palettes/')),
                ('ai_prompt_hint', models.TextField()),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='app.theme')),
            ],
        ),
    ]
